import { readFileSync, writeFileSync, readdirSync, unlinkSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..', '..', '..');
const CLAUDE_MD = join(ROOT, 'CLAUDE.md');
const RULES_DIR = join(ROOT, '.cursor', 'rules');

const SECTION_MAP = [
  {
    match: /^## 1\.\s*中文输出/,
    file: 'proj-chinese.mdc',
    description: '中文输出规范',
    alwaysApply: true,
  },
  {
    match: /^## 2\.\s*代码修改后自动构建/,
    file: 'build-after-edit.mdc',
    description: '代码修改后必须执行构建',
    globs: 'src/**/*.ts',
  },
  {
    match: /^## 3\.\s*日志约束/,
    file: 'logging-rules.mdc',
    description: '日志只能用 src/logger.ts，禁止 console 和第三方日志库',
    globs: 'src/**/*.ts',
  },
  {
    match: /^## 4\.\s*平台同步修改/,
    file: 'platform-sync.mdc',
    description: 'Figma 与 MasterGo 渲染器必须同步修改',
    globs: 'src/platform/**',
  },
  {
    match: /^## 5\.\s*导入.*导出对称性/,
    file: 'roundtrip-fidelity.mdc',
    description: '导入与导出必须对称，确保 PSD round-trip 保真',
    globs: 'src/parser/**,src/exporter/**,src/ir/**,src/platform/**',
  },
  {
    match: /^## 6\.\s*Git 提交信息/,
    file: 'git-commit.mdc',
    description: 'Git 提交信息格式：单行英文 Conventional Commits',
    alwaysApply: true,
  },
  {
    match: /^## 7\.\s*代码检索路由/,
    file: 'code-intel-routing.mdc',
    description: '代码检索路由：结构走 codegraph，概念走 graphify，模糊走内置语义检索',
    globs: 'src/**',
  },
];

const GENERATED_TAG = '<!-- generated by sync-rules -->';

function splitSections(markdown) {
  const lines = markdown.split('\n');
  const sections = [];
  let current = null;

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (current) sections.push(current);
      current = { heading: line, body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) sections.push(current);
  return sections;
}

function buildFrontmatter(config) {
  const lines = ['---'];
  lines.push(`description: "${config.description}"`);
  if (config.globs) {
    lines.push(`globs: ${config.globs}`);
    lines.push('alwaysApply: false');
  } else {
    lines.push('alwaysApply: true');
  }
  lines.push('---');
  return lines.join('\n');
}

function trimTrailingBlanks(text) {
  return text.replace(/\n{3,}/g, '\n\n').replace(/\n+$/, '\n');
}

function generate() {
  const markdown = readFileSync(CLAUDE_MD, 'utf-8');
  const sections = splitSections(markdown);

  mkdirSync(RULES_DIR, { recursive: true });

  const generatedFiles = new Set();
  const results = [];

  for (const config of SECTION_MAP) {
    const section = sections.find(s => config.match.test(s.heading));
    if (!section) {
      results.push(`  SKIP  ${config.file} (section not found)`);
      continue;
    }

    const title = section.heading.replace(/^## \d+\.\s*/, '# ');
    const body = trimTrailingBlanks(section.body.join('\n'));
    const content = [
      GENERATED_TAG,
      buildFrontmatter(config),
      '',
      title,
      '',
      body,
    ].join('\n');

    const outPath = join(RULES_DIR, config.file);
    writeFileSync(outPath, content, 'utf-8');
    generatedFiles.add(config.file);
    results.push(`  WRITE ${config.file}`);
  }

  const existing = readdirSync(RULES_DIR).filter(f => f.endsWith('.mdc'));
  for (const f of existing) {
    if (generatedFiles.has(f)) continue;
    const filePath = join(RULES_DIR, f);
    const content = readFileSync(filePath, 'utf-8');
    if (content.startsWith(GENERATED_TAG)) {
      unlinkSync(filePath);
      results.push(`  CLEAN ${f} (stale)`);
    }
  }

  console.log(`sync-rules: ${generatedFiles.size} files generated from CLAUDE.md`);
  for (const r of results) console.log(r);
}

generate();
